server:
  port: 9091
spring:
  application:
    name: gateway-message
  zipkin:
    base-url: http://localhost:9098
    sleuth:
      sampler:
        percentage: 1 #zipkin采样率，默认为0.1，改为1后全采样，但是会降低接口调用效率
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/