server:
  port: 8083
spring:
  application:
    name: gateway-message
#  zipkin:
#    base-url: http://localhost:9098
  zipkin:
    sender:
      type: kafka
  sleuth:
    sampler:
      percentage: 1.0 #zipkin采样率，默认为0.1，改为1后全采样，但是会降低接口调用效率
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.104:9092  #ip地址根据实际kafka集群地址
          zk-nodes: 192.168.1.104:2181
#          auto-add-partitions: true
#          auto-create-topics: true
#          min-partition-count: 1
#      bindings:
#        output:
#          destination: zipkin-server
#          content-type: text/plain
#          producer:
#            partitionCount: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/