server:
  port: 9098
spring:
  application:
    name: gateway-zipkin
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.104:9092  #ip地址根据实际kafka集群地址
          zk-nodes: 192.168.1.104:2181
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://127.0.0.1:9200
      username: elastic
      password:
      cluster: elasticsearch
      index: zipkin
      index-shards: 1
      index-replicas: 1
  collector:
    kafka:
      bootstrap-servers: 192.168.1.104:9092
      zookeeper: 192.168.1.104:2181
      topic: sleuth
      group-id: sleuth