server:
  port: 9098
spring:
  application:
    name: gateway-zipkin
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9400  #ip地址根据实际kafka集群地址
          zkNodes: 127.0.0.1:2181
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://127.0.0.1:9200
      username: elastic
      password:
      cluster: elasticsearch
      index: zipkin
      index-shards: 1
      index-replicas: 1