server:
  port: 9098
spring:
  application:
    name: gateway-zipkin
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9400  #ip地址根据实际kafka集群地址
          zk-nodes: 127.0.0.1:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        input:
          destination: event-demo
          group: s1
          consumer:
            autoCommitOffset: false
            concurrency: 1
            partitioned: false
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://127.0.0.1:9200
      username: elastic
      password:
      cluster: elasticsearch
      index: zipkin
      index-shards: 1
      index-replicas: 1