server:
  port: 8888
spring:
  application:
    name: gateway-discovery
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    server:
        waitTimeInMsWhenSyncEmpty: 0