server:
  port: 8084
spring:
  application:
    name: gateway-rest
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  zipkin:
    base-url: http://localhost:9098
  sleuth:
    sampler:
      percentage: 1 #zipkin采样率，默认为0.1，改为1后全采样，但是会降低接口调用效率
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9400  #ip地址根据实际kafka集群地址
          zkNodes: 127.0.0.1:2181
zuul:
  ignoredServices: '*'
  routes:
    account:
      path: /api/gateway/account/**
      serviceId: gateway-account
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/