server:
  port: 9092
spring:
  application:
    name: gateway-account
  zipkin:
    base-url: http://localhost:9098
  sleuth:
    sampler:
      percentage: 1 #zipkin采样率，默认为0.1，改为1后全采样，但是会降低接口调用效率
  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9400  #ip地址根据实际kafka集群地址
          zk-nodes: 127.0.0.1:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        output:
          destination: event-demo
          content-type: text/plain
          producer:
            partitionCount: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
feign:
  hystrix:
    enabled: true #开启熔断